plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    // Lazy DFU
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    // Jei, Cucumber, Botany Pots, Bookshelf, Ender Storage, Code Chicken Lib, The One Probe
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            forRepositories(fg.repository)
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }
    // Ender Storage, Code Chicken Lib
    maven {
        url = "https://maven.covers1624.net"
    }
    // Botany Pots
    maven {
        url = "https://maven.blamejared.com"
    }
}

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }

        server {
            args '--nogui'
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // JEI (to view recipes)
    runtimeOnly fg.deobf("maven.modrinth:jei:k3W3h9cO")
    compileOnly fg.deobf("mezz.jei:jei-1.17.1:8.3.1.1002:api")

    // Lazy DFU for faster game start
    runtimeOnly fg.deobf("curse.maven:lazy-dfu-forge-460819:3544496")

    // Cucumber Library (to view Tags)
    runtimeOnly fg.deobf("maven.modrinth:cucumber:gPnt4RpR")

    // Botany Pots
    runtimeOnly fg.deobf("maven.modrinth:botany-pots:jieavSfv")
    implementation fg.deobf("net.darkhax.botanypots:BotanyPots-Common-1.18.2:8.1.28")
    implementation fg.deobf("net.darkhax.botanypots:BotanyPots-Forge-1.18.2:8.1.28")
    // Bookshelf dependency
    runtimeOnly fg.deobf("maven.modrinth:bookshelf-lib:dPZreKSP")
    implementation fg.deobf("net.darkhax.bookshelf:Bookshelf-Common-1.18.2:13.3.56")
    implementation fg.deobf("net.darkhax.bookshelf:Bookshelf-Forge-1.18.2:13.3.56")

    // Ender Storage
    runtimeOnly fg.deobf("maven.modrinth:ender-storage:klK0FXvK")
    implementation fg.deobf("codechicken:EnderStorage:1.18.2-2.9.0.182:universal")
    // Code Chicken Lib dependency
    runtimeOnly fg.deobf("maven.modrinth:codechicken-lib:DKyMgZwQ")
    implementation fg.deobf("codechicken:CodeChickenLib:1.18.2-4.1.4.488:universal")

    // TOP (The one probe)
    runtimeOnly fg.deobf("maven.modrinth:the-one-probe:pWurhZji")
    compileOnly fg.deobf("maven.modrinth:the-one-probe:pWurhZji")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(['Specification-Title'     : mod_id,
                    'Specification-Vendor'    : mod_authors,
                    'Specification-Version'   : '1',
                    'Implementation-Title'    : project.name,
                    'Implementation-Version'  : project.jar.archiveVersion,
                    'Implementation-Vendor'   : mod_authors,
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }
    finalizedBy 'reobfJar'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
