org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,26)

neo_version=21.1.216
loader_version_range=[1,)

mod_id=enderbotanypots
mod_name=Ender Botany Pots
mod_license=LGPL v2.1
mod_version=1.21.1-0.0.1
mod_group_id=eu.wxrlds.enderbotanypots
mod_authors=Wxrlds
mod_description=Botany Pots meets Ender Storage. Transfer your Botany Pots harvest directly into your Ender Storage Network.
