org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=enderbotanypots
mod_name=Ender Botany Pots
mod_license=LGPL v2.1
mod_version=1.20.1-0.1.1
mod_group_id=eu.wxrlds.enderbotanypots
mod_authors=Wxrlds
mod_description=The dimensions collide. Botany Pots redirect their output directly into Ender Storage
