modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Wxrlds/EnderBotanyPots"

# Ender Botany Pots
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Wxrlds/EnderBotanyPots"
credits = "Darkhax for Botany Pots and covers1624 for Ender Storage"
authors = "${mod_authors}"
description = '''${mod_description}'''

# NeoForge
[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

# Minecraft
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Botany Pots
[[dependencies.${ mod_id }]]
modId = "botanypots"
type = "required"
versionRange = "[1.21.1-21,)"
ordering = "NONE"
side = "BOTH"

# Ender Storage
[[dependencies.${ mod_id }]]
modId = "enderstorage"
type = "required"
versionRange = "[1.21.1-2.13,)"
ordering = "NONE"
side = "BOTH"

# Botany Pots Tiers
[[dependencies.${ mod_id }]]
modId = "botanypotstiers"
type = "optional"
versionRange = "[7,)"
ordering = "AFTER"
side = "BOTH"