name: "build-commit"

on:
  push:
    branches:
      - "**" # All branches but not on tags

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Get mod info"
        id: "info"
        shell: bash
        run: |
          chmod +x .github/scripts/get_mod_info.sh
          .github/scripts/get_mod_info.sh

      - name: "Setup JDK ${{ steps.info.outputs.java_version }}"
        uses: "actions/setup-java@v5"
        with:
          java-version: "${{ steps.info.outputs.java_version }}"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: "gradle/actions/setup-gradle@v5"
        with:
          cache-read-only: false

      - name: "Build with Gradle"
        run: |
          ./gradlew build

      - name: "Extract current branch name"
        id: "get_branch"
        run: |
          ref="${GITHUB_REF#refs/heads/}"
          echo "branch=${ref////-}" >> $GITHUB_OUTPUT

      - name: "Upload artifacts"
        uses: "actions/upload-artifact@v7"
        with:
          name: "${{ steps.info.outputs.mod_id }}-artifacts-${{ steps.get_branch.outputs.branch }}-${{ github.run_number }}"
          path: build/libs/*.jar
