name: "build-release"

on:
  push:
    tags:
      - "alpha/v**"
      - "beta/v**"
      - "release/v**"

jobs:
  release:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 0

      - name: "Get mod info"
        id: "info"
        shell: bash
        run: |
          chmod +x .github/scripts/get_mod_info.sh
          .github/scripts/get_mod_info.sh

      # This makes sure that when there is a tag push, the version in gradle.properties has been increased
      - name: "Validate version bump on tag"
        run: |
          CUR_VER=${{ steps.info.outputs.mod_version }}
          PREV_VER=${{ steps.info.outputs.previous_mod_version }}
          if [ "$PREV_VER" != "none" ] && [ "$CUR_VER" == "$PREV_VER" ]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "::error::VERSION in gradle.properties NOT UPDATED!"
            echo "::error::Expected version bump in gradle.properties but received $CUR_VER (same as in tag ${{ steps.info.outputs.previous_tag }})."
            echo "::error::Deleting tag '$TAG_NAME' and failing build..."

            # Delete the tag from the remote
            git push origin ":refs/tags/$TAG_NAME"
            exit 1
          fi

      - name: "Setup JDK ${{ steps.info.outputs.java_version }}"
        uses: "actions/setup-java@v5"
        with:
          java-version: "${{ steps.info.outputs.java_version }}"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: "gradle/actions/setup-gradle@v6"
        with:
          cache-read-only: true

      - name: "Build with Gradle"
        run: |
          ./gradlew build

      - name: "Upload to Modrinth"
        if: ${{ vars.MR_PROJECT_ID != '' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ vars.MR_PROJECT_ID }}
          modrinth-token: ${{ secrets.MR_PROJECT_API_TOKEN }}

          name: ${{ steps.info.outputs.mod_name }}-${{ steps.info.outputs.mod_version }}
          game-versions: |
            ${{ steps.info.outputs.minecraft_version }}
          loaders: |
            ${{ steps.info.outputs.mod_loader }}
          version-type: ${{ steps.info.outputs.mod_release_type }}
          version: ${{ steps.info.outputs.minecraft_version }}-${{ steps.info.outputs.mod_version }}
          modrinth-files: build/libs/*.jar

          changelog: |
            ${{ steps.info.outputs.minecraft_version }}-${{ steps.info.outputs.mod_version }}

            [Need a server? Just click on the Picture, use the code WXRLDS for 25% off of your first month and play with your friends!](https://bisecthosting.com/Wxrlds)

            [![Bisect Hosting](https://www.bisecthosting.com/partners/custom-banners/7ac5059a-f314-47ac-8598-45d00bd20eb4.png)](https://bisecthosting.com/Wxrlds)

            ${{ steps.info.outputs.changelog }}

          modrinth-dependencies: |
            botany-pots(required)
            ender-storage(required)
            the-one-probe(optional)
            jei(optional)
            botany-pots-tiers(optional)

      - name: "Upload to CurseForge"
        if: ${{ vars.CF_PROJECT_ID != '' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{ vars.CF_PROJECT_ID }}
          curseforge-token: ${{ secrets.CF_PROJECT_API_TOKEN }}

          name: ${{ steps.info.outputs.mod_name }}-${{ steps.info.outputs.mod_version }}
          game-versions: |
            ${{ steps.info.outputs.minecraft_version }}
          loaders: |
            ${{ steps.info.outputs.mod_loader }}
          version-type: ${{ steps.info.outputs.mod_release_type }}
          version: ${{ steps.info.outputs.minecraft_version }}-${{ steps.info.outputs.mod_version }}
          curseforge-files: build/libs/*.jar

          changelog: |
            ${{ steps.info.outputs.minecraft_version }}-${{ steps.info.outputs.mod_version }}

            [Need a server? Just click on the Picture, use the code WXRLDS for 25% off of your first month and play with your friends!](https://bisecthosting.com/Wxrlds)

            [![Bisect Hosting](https://www.bisecthosting.com/partners/custom-banners/7ac5059a-f314-47ac-8598-45d00bd20eb4.png)](https://bisecthosting.com/Wxrlds)

            ${{ steps.info.outputs.changelog }}

          curseforge-dependencies: |
            botany-pots(required)
            ender-storage-1-8(required)
            the-one-probe(optional)
            jei(optional)
            botany-pots-tiers(optional)
